# Generated by Django 6.1.1 on 2026-09-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expensedetail',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
